### ISSUE TITLE
GeoJSON Object is Freezing my Machine

### ISSUE THREAD

**Issue by iiVi** [iiVi/parkly#3]
@harimohanraj89 @DrRobotmck @williamfshaw @bigtone1284

I'm trying to work with GeoJSONs to render cool data to my leaflet map.  After converting a .shp (GIS shape file) to GeoJSON, I try to open it in Sublime Text to add a line.  However, Sublime freezes before ever displaying the file.  Text Editor can open and display it after a few minutes, but takes several minutes to even register a keystroke.  

How can I better deal with huge JSON files?

**Comment by WilliamfShaw** [comment]
@iiVi New Computer?????? 

@bigtone1284 heading down now
